### ISSUE TITLE
Configuration step fails for CentOS7 if no ssh packages were installed

### ISSUE THREAD

**Issue by ghost** [willshersystems/ansible-sshd#111]
When using the role to install sshd in a centos7 Docker container the role installs the packages, but the sshd is never started before the "Configuration" step.

Due to this there are no hostkeys, which seem to be generated when sshd is started for the first time and there are no keys yet:
```TASK [willshersystems.sshd : Configuration] ************************************
fatal: [localhost]: FAILED! => {"changed": false, "checksum": "3eb484dee3405d49871d72d546e490cd0a6bf897", "exit_status": 1, "msg": "failed to validate", "stderr": "Could not load host key: /etc/ssh/ssh_host_rsa_key\r\nCould not load host key: /etc/ssh/ssh_host_ed25519_key\r\nsshd: no hostkeys available -- exiting.\r\n", "stderr_lines": ["Could not load host key: /etc/ssh/ssh_host_rsa_key", "Could not load host key: /etc/ssh/ssh_host_ed25519_key", "sshd: no hostkeys available -- exiting."], "stdout": "", "stdout_lines": []}
```

I thought about just fixing this, but this seems more complicated, as one would have to actually dig through the sshd_config.hostkey variable to find the expected name for the hostkeys and actually figure out the type for the hostkey and then generate them, if they do not exist.

Another idea would be to unconditionally start sshd before the configuration step, to ensure the existence of the hostkeys, but I do not know if this may create other problems.

This is a rather special corner case, as ansible works over SSH and so this will only ever be a problem, when setting up a container or any situation where the playbook does not rely on sshd actually running (ansible_connection=local e.g.).

If simply unconditionally starting sshd before the configuration step would be an option (or just doing this under certain conditions) I could come up with a quick PR.

Any ideas or suggestions?

**Comment by pdreker** [comment]
This issue was opened by me - I had to shuffle GitHub accounts around and the original one went the way of the Dodo...

Another option would be to call "ssh-keygen -A" which will automatically generate all missing SSH host keys, which the installed version supports.

**Comment by mattwillsher** [comment]
This was an issue from the early days of the role. I seem to recall I did try to generate the keys, but given the issues, as you state, I decided not to. 

Perhaps code could be added to generate keys based on data passed into the role? 
Alternatively, maybe the check could be optional? 

For my learning, what's the use case for installing ssh into a docker container?

**Comment by pdreker** [comment]
What is the use case...? Good question ;-)
I stumbled across the problem when setting up Travis CI test scaffolds for some of my Ansible roles, which run my role (which depends on your role) against containers...

My intention in opening this issue was more to ask, if there may be a simple workaround which might remove a silly corner case. Given that solving this may require adding more variables into the role and complicate some things quite a lot, I'd be inclined to just mark this as "wontfix". I ended up just not running the affected role against the CentOS containers and be done with that. Leaving this issue as documentation of the fact that there is a "degenerate corner case" is probably enough.

**Comment by mattwillsher** [comment]
Looking at the openssh-server package, there is a unit file `/usr/lib/systemd/system/sshd-keygen.service`, which in turn calls `/usr/sbin/sshd-keygen`. That script generates the keys. It requires the initscripts package for `/etc/rc.d/init.d/functions`. Pretty messy for a container.

**Comment by crlane** [comment]
This also effects ubuntu 20.04
