### ISSUE TITLE
PR #121 caused Ansible 2.8+ requirement

### ISSUE THREAD

**Issue by mattwillsher** [willshersystems/ansible-sshd#123]
PR #121 introduced support for functionality only support in Ansible >2.7, breaking compatibility with old versions. Given the nature of the change, it will be reverted in #122 and can be reapplied once 2.7 is well out of support.

**Comment by ahmadalli** [comment]
isn't it possible to merge both solutions and assert for ansible < 2.8 `ansible_version.full is version_compare('2.8', '>=')` and exit_host for ansibme >= 2.8?

**Comment by mattwillsher** [comment]
I'm happy to take a PR along those lines. I'm rather just maintaining this code these days as I've not used Ansible for the last year, so am not up to date with current practices.

**Comment by mattwillsher** [comment]
As is stands, I'm planning on reverting and pushing a new release until I or someone else comes up with a better fix, or Ansible 2.7 is no longer a major concern.

**Comment by mattwillsher** [comment]
v0.8.3 released with the change reverted.

**Comment by mattwillsher** [comment]
As of v0.10.0, Ansible 2.8 is the minimal supported version.

**Comment by mattwillsher** [comment]
See #129
