### ISSUE TITLE
CentOS 8 / EL 8 problem

### ISSUE THREAD

**Issue by lentferj** [willshersystems/ansible-sshd#140]
sshd on CentOS8 seems to be not configured through /etc/ssh/sshd_config, but loads /etc/crypto-policies/back-ends/opensshserver.config via the systemd sshd.service configuration. So while you can use this role to manage /etc/ssh/sshd_config, it won't take effect.

**Comment by lentferj** [comment]
The "problem" (if one like to call it that) seem to be "system-wide cryptographic policies" in EL8, which take precedence over some settings in sshd_config (ciphers, mac, etc). If you want to return the control back to sshd_config you need to uncomment the line with the CRYPTO_POLICY= variable in the /etc/sysconfig/sshd file according to the section OpenSSH on the lower half of this page
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/security_hardening/using-the-system-wide-cryptographic-policies_security-hardening

Having an option to set this via the role would be nice

**Comment by Jakuje** [comment]
The sshd is still configured through `sshd_config` in RHEL8, but only crypto-related configuration is overridden on the command-line by crypto policy to allow setting this system-wide.

I am not sure if this is something that should come here as if you are targeting some particular cryptographic configuration or compliance, you should update the crypto policies directly [1]. But I understand it can be handy and quite common request. What do you think @mattwillsher ?

[1] https://www.redhat.com/en/blog/how-customize-crypto-policies-rhel-82

**Comment by lentferj** [comment]
I tried changing just the sshd settings with crypto-policies. If I have not overseen anything, if you want to change the settings for just one service, you have to set up your changes in /etc/crypto-policies/local.d, e.g. which in the case of sshd will then be appended to what is defined in /etc/crypto-policies/back-ends/opensshserver.config.

So, to change the crypto setup for opensshserver, I would add something like:

\# cat /etc/crypto-policies/local.d/opensshserver-local_conf.config 
' -oCiphers=chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr -oMACs=hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256 -oHostKeyAlgorithms=ssh-ed25519,rsa-sha2-512,rsa-sha2-256, -oKexAlgorithms=curve25519-sha256,diffie-hellman-group18-sha512,diffie-hellman-group16-sha512,diffie-hellman-group-exchange-sha256'

because it's appended and does not override what is in /etc/crypto-policies/back-ends/opensshserver.config, I end up with a sshd process having everything configured doubled, with the later setting taking preference.

\# ps -ef | grep /usr/sbin/sshd
root       25354       1  0 15:31 ?        00:00:00 /usr/sbin/sshd -D **-oCiphers**=aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes256-ctr,aes256-cbc,aes128-gcm@openssh.com,aes128-ctr,aes128-cbc **-oMACs**=hmac-sha2-256-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha1,umac-128@openssh.com,hmac-sha2-512 -oGSSAPIKexAlgorithms=gss-gex-sha1-,gss-group14-sha1- -oKexAlgorithms=curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1 -oHostKeyAlgorithms=rsa-sha2-256,rsa-sha2-256-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384,ecdsa-sha2-nistp384-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-512-cert-v01@openssh.com,ecdsa-sha2-nistp521,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,ssh-rsa,ssh-rsa-cert-v01@openssh.com -oPubkeyAcceptedKeyTypes=rsa-sha2-256,rsa-sha2-256-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384,ecdsa-sha2-nistp384-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-512-cert-v01@openssh.com,ecdsa-sha2-nistp521,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,ssh-rsa,ssh-rsa-cert-v01@openssh.com -oCASignatureAlgorithms=rsa-sha2-256,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,rsa-sha2-512,ecdsa-sha2-nistp521,ssh-ed25519,ssh-rsa **-oCiphers**=chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr **-oMACs**=hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256 -oHostKeyAlgorithms=ssh-ed25519,rsa-sha2-512,rsa-sha2-256, -oKexAlgorithms=curve25519-sha256,diffie-hellman-group18-sha512,diffie-hellman-group16-sha512,diffie-hellman-group-exchange-sha256


In my opinion this is ugly compared to just using sshd_config as "usual". But really, I may be overseeing options with the crypto-policies framework here.

**Comment by mattwillsher** [comment]
I think CRYPTO_POLICY in /etc/sysconfig/sshd should be supported, along with any other options in there and the crypto policy support, if it's something people want to (or are forced to) use on a major distro. I'm happy to pick up /etc/sysconfig/sshd

**Comment by Jakuje** [comment]
@lentferj I meant if you are interested in disabling particular algorithms, you can create your own crypto policy which will be applied not only to ssh, but also to TLS and other cryptographic protocols used in your system (see the previous link). The `/etc/sysconfig/sshd` file is generally suggested to set the to nothing as `CRYPTO_POLICY=` to replace crypto policy and pick up whatever comes from configuration file as usual a described in the manual pages for crypto policies [1].

I will certainly have a look into this sooner or later as it sounds like quite a common use case. In Fedora 32+ it is already achieved by `Include` keyword, which is more transparent and much easier to override. But when we were putting RHEL8 together, this was not an option.

[1] https://gitlab.com/redhat-crypto/fedora-crypto-policies/-/blob/rhel8/update-crypto-policies.8.txt#L170
[2] https://gitlab.com/redhat-crypto/fedora-crypto-policies/-/blob/master/update-crypto-policies.8.txt#L172

**Comment by mattwillsher** [comment]
This is implemented in #142
