### ISSUE TITLE
apt: error while evaluating conditional

### ISSUE THREAD

**Issue by christiansmith** [willshersystems/ansible-sshd#15]
I'm new to ansible so please forgive my ignorance in advance. When I add this role to my playbook and run it against a node I get the following:

```
TASK: [willshersystems.apt | Update apt cache] ********************************
fatal: [anvil-connect] => error while evaluating conditional: ansible_pkg_mgr == 'apt' and apt_has_run is not defined

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/smith/playbook.retry

anvil-connect              : ok=9    changed=3    unreachable=1    failed=0
```

This is the case with or without including the apt role explicitly.

```
  roles:
    - common
    - willshersystems.apt
    - willshersystems.sshd
```

**Comment by mattwillsher** [comment]
Sorry for the delay in getting back to you.

Have you checked out the willshersystems.apt repo in the same location as willshersystems.sshd?

Can you let me know the Ansible version and os you're running on so I can troubleshoot please?

I think there was a request to remove the apt dependency so I can look into that. I'm not sure why I included willshersystems.apt in the first place..

**Comment by mattwillsher** [comment]
I've just found the PR that removes that dependency. I'm just releasing 0.3.0 which contains the fix.

**Comment by christiansmith** [comment]
Thanks!
