### ISSUE TITLE
publish latest release v0.14.1 to ansible galaxy

### ISSUE THREAD

**Issue by pescobar** [willshersystems/ansible-sshd#181]
Is there any reason why latest `v0.14.1` is not published to https://galaxy.ansible.com/willshersystems/sshd ?

**Comment by Jakuje** [comment]
@mattwillsher ?

The difference between 0.14.1 and 0.14.0 is very small and only about the ansible managed comment which we did not consider important enough for a release:

https://github.com/willshersystems/ansible-sshd/compare/v0.14.0...v0.14.1

But we landed couple of other changes and I have couple of more in the plans for next weeks so I assume we should release 0.15.0 and publish it in galaxy soon.

**Comment by mattwillsher** [comment]
I've added v0.14.1 - not sure why that didn't get added at the time.
