### ISSUE TITLE
The sshd service is not reloading on KVM virtual machines

### ISSUE THREAD

**Issue by andybro19** [willshersystems/ansible-sshd#186]
**Problem**

When this role is applied to a host that is a KVM virtual machine, the SSH service is not reloaded after changes have been made. Also, it doesn't ensure the SSH service is enabled. The output of running this role on a KVM VM is shown below:

```
TASK [willshersystems.sshd : Service enabled and running] *************************************************************************************************************************************************
skipping: [debian-bullseye]
...
RUNNING HANDLER [willshersystems.sshd : Reload the SSH service] *******************************************************************************************************************************************
skipping: [debian-bullseye]
```

This is due to theses conditions under tasks: [Service enabled and running](https://github.com/willshersystems/ansible-sshd/blob/753073f4d6928526c21e8f24050c30318cd51068/tasks/install_service.yml#L37) and [Reload the SSH service](https://github.com/willshersystems/ansible-sshd/blob/753073f4d6928526c21e8f24050c30318cd51068/handlers/main.yml#L9), and that `kvm` is included in [__sshd_skip_virt_env](https://github.com/willshersystems/ansible-sshd/blob/753073f4d6928526c21e8f24050c30318cd51068/vars/common.yml#L1).

**Expected result**

I would expect that this role can be applied to virtual machines of all types, including kvm, and that it would ensure the service is enabled and reloads sshd when changes have been made.

While containers generally don't run systemd, which is the reason I suspect this behaviour has been added, VMs normally do run systemd.

**Comment by rstory** [comment]
I was coming here to report this. You should also check ansible_virtualization_role is guest and not host. I added some debug, and here are two runs - one on my laptop, and a second on a VM on my laptop:

- hardware host (with virtualization enabled)
```text
TASK [sshd.willshersystems : debug] ****************************************************************************************************************************
task path: /home/rstory/ansible/roles/sshd.willshersystems/tasks/install_service.yml:30
ok: [p1g4] => {
    "sshd_manage_service": true
}

TASK [sshd.willshersystems : debug] ****************************************************************************************************************************
task path: /home/rstory/ansible/roles/sshd.willshersystems/tasks/install_service.yml:31
ok: [p1g4] => {
    "ansible_virtualization_type": "kvm"
}

TASK [sshd.willshersystems : debug] ****************************************************************************************************************************
task path: /home/rstory/ansible/titan/sshd.willshersystems/tasks/install_service.yml:32
ok: [p1g4] => {
    "ansible_virtualization_role": "host"
}
```

- vm host
```text
TASK [sshd.willshersystems : debug] ****************************************************************************************************************************
task path: /home/rstory/ansible/roles/sshd.willshersystems/tasks/install_service.yml:31
ok: [c7-min-TVM] => {
    "ansible_virtualization_type": "kvm"
}

TASK [sshd.willshersystems : debug] ****************************************************************************************************************************
task path: /home/rstory/ansible/roles/sshd.willshersystems/tasks/install_service.yml:32
ok: [c7-min-TVM] => {
    "ansible_virtualization_role": "guest"
}
```

**Comment by rstory** [comment]
actually my issue is a little different, as it wasn't reloading on hardware with virtualization modules loaded. I found the hint to check virtualization role in this bug: https://github.com/ansible/ansible/issues/74831#issuecomment-853309183

I had this patch that fixed my issue:

```text
diff --git tasks/install_service.yml tasks/install_service.yml
index ead7701..268440d 100644
--- tasks/install_service.yml
+++ tasks/install_service.yml
@@ -34,7 +34,7 @@
     state: started
   when:
     - sshd_manage_service|bool
-    - ansible_virtualization_type|default(None) not in __sshd_skip_virt_env
+    - ansible_virtualization_role == 'guest' and ansible_virtualization_type|default(None) not in __sshd_skip_virt_env
     - ansible_connection != 'chroot'
```

Another fix for the original poster's issue would be to have a bool to configure when to skip. eg

```text
$ git diff
diff --git defaults/main.yml defaults/main.yml
index 045270c..5a3a1e6 100644
--- defaults/main.yml
+++ defaults/main.yml
@@ -6,6 +6,9 @@ sshd_enable: true
 # Don't apply OS defaults when set to true
 sshd_skip_defaults: false
 
+# Don't enable/start service in virtual environments
+sshd_skip_virt_env: false
+
 # If the below is false, don't manage the service or reload the SSH
 # daemon at all
 sshd_manage_service: true
diff --git tasks/install_service.yml tasks/install_service.yml
index ead7701..85f01ac 100644
--- tasks/install_service.yml
+++ tasks/install_service.yml
@@ -34,7 +34,7 @@
     state: started
   when:
     - sshd_manage_service|bool
-    - ansible_virtualization_type|default(None) not in __sshd_skip_virt_env
+    - sshd_skip_virt_env|bool and ansible_virtualization_role == 'guest' and ansible_virtualization_type|default(None) not in __sshd_skip_virt_env
     - ansible_connection != 'chroot'
 
 # Due to ansible bug 21026, cannot use service module on RHEL 7
```

**Comment by Jakuje** [comment]
I do not think the kvm is a synonym for something where we should prevent the reloads so I still think we should apply #187 and remove the `kvm` from the list. Adding another exception `kvm`/`host` would just leave the `kvm`/`guest` to explode later. And I do not think the reload should be skipped on KVM virtual machines.
