### ISSUE TITLE
code clarification

### ISSUE THREAD

**Issue by kostyrevaa** [willshersystems/ansible-sshd#19]
Hello, Matt!
thanks for the terrific role!
I'm ansible newbie so I don't quite understand your code.
What this file ansible-sshd/meta/make_option_list is for?
When it comes to play?
there's only ansible-sshd/meta/main.yml described in docs.
What are other files there for?
thanks in advance!

**Comment by mattwillsher** [comment]
Hi kostyrevaa,

Glad you like the role!

They are there to generate the the templates/sshd_config.j2 . By amending the options_body and options_match files the running make_option_list it generates the template file. The options_body file I also generated programmatically and then tune.

I'll leave this issue open to remind me to add a README to the meta directory.

**Comment by mattwillsher** [comment]
Added note to README.md under #24
