### ISSUE TITLE
chore(linting): update variable names to include sshd_ prefix

### ISSUE THREAD

**Issue by mattwillsher** [willshersystems/ansible-sshd#246]
Var names should be prefixed with role name to pass lint checks.

If no time to work on this check can be disabled for now.

**Comment by Jakuje** [comment]
This was disabled in 34be8e5ea372f25c4ed643340e8b9416eeae0738 if I see right

**Comment by mattwillsher** [comment]
The lint issue I've come across recently on a new role but try as I might I couldn't get the name to comply. 
I do believe that we should conform to this rule, though, as it's effectively a variable scoping challenge. 

I'll leave this open for now as a reminder to myself.

**Comment by spetrosi** [comment]
In system roles, we deprecated old variables by printint a message to users who use those old variables, and then setting the correct variable name, see https://github.com/linux-system-roles/mssql/blob/main/tasks/main.yml#L12-L25
Then, maybe in a couple years, we can remove the deprecated variable completely.

**Comment by Jakuje** [comment]
This was resolved with #299. Closing.
