### ISSUE TITLE
DebianBanner option in sshd_config

### ISSUE THREAD

**Issue by tissieres** [willshersystems/ansible-sshd#25]
Hello,
On Debian systems, there is a DebianBanner directive that can be set in sshd_config:

DebianBanner
             Specifies whether the distribution-specified extra version suffix is included during initial protocol handshake.  The default is “yes”.

Can you add it to your template?
Thanks

**Comment by mattwillsher** [comment]
Hi there, yes, I'll get that added.

**Comment by tissieres** [comment]
Thanks a lot!

**Comment by mattwillsher** [comment]
This has been added and 0.3.2 released to Galaxy with the fix.

**Comment by tissieres** [comment]
Thank you Matt !
