### ISSUE TITLE
Support needed for Ubuntu 24.04

### ISSUE THREAD

**Issue by swapnilnshelar** [willshersystems/ansible-sshd#291]
When running this playbook on Ubuntu 24.04 [Noble Numbat], the playbooks stops in the following task, Ubuntu 24.04 being and LTS release and widely used, i am sure you must be having a plan in place, would like to know if you have any timeline in mind, thanks.

TASK [willshersystems.sshd : OS is supported] ************************************************************************************************************************************************

**Comment by mattwillsher** [comment]
Hi @swapnilnshelar - work is under way in #290 .

**Comment by mattwillsher** [comment]
Fixed in #290 , released as v0.24.0
