### ISSUE TITLE
sshd restart required after crypto policy update

### ISSUE THREAD

**Issue by meta-metaferia** [willshersystems/ansible-sshd#302]
On RHEL8, when these variables are set to `true`
```
sshd_sysconfig: true
sshd_sysconfig_override_crypto_policy: true
```
It goes and update this file `/etc/sysconfig/sshd` . However, at the end of the role execution it only does an sshd reload which is not enough for the change made inside  `/etc/sysconfig/sshd` to take effect, a restart of the sshd service is required.

**Comment by Jakuje** [comment]
Good catch! Sorry for a delay though. I filled #303. Can you check it will solve your issue?
