### ISSUE TITLE
No support for configuration changes

### ISSUE THREAD

**Issue by thorstenkampe** [willshersystems/ansible-sshd#36]
It looks like there is no support for the simple task of changing an existing configuration option without regenerating the whole configuration from a default. That limits the usefulness of this role severely.

**Comment by mattwillsher** [comment]
The role is designed to completely rebuild the ssh configuration to a known state. It allows any and all options to be changed. For example, it is possible to simply set PasswordAuthentication to no only and the rest of the config will stay at the default for the OS version as per the default setting in this role

I'm happy to take suggestions on changes to the code base that would achieve your aims.

**Comment by thorstenkampe** [comment]
I don't know ansible-sshd's code base so I can't really tell whether my request would require a complete redesign.

In principle the only change required would be that you don't start from an OS default `sshd_config` but use the existing file.

**Comment by mattwillsher** [comment]
It's fundamental design decision that the entire file gets replaced. This is to ensure any local changes get reverted, the file is always in a known good state and to ensure the change is applied quickly.

For adhoc changes to the file, the lineinfile module may be suitable.

**Comment by mattwillsher** [comment]
No further feedback so closing.
