### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by dphilpot** [willshersystems/ansible-sshd#38]
Hi Willsher,

with the latest ansible version (2.0.1.0) we get a deprecation warning.

example:
`[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{sshd_packages}}'). This feature will be removed in a future
 release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.`

**Comment by mattwillsher** [comment]
0.4.3 released with the fix from @haraldkoch

Thanks for the report.
