### ISSUE TITLE
sshd_manage_var_run not necessary on Fedora

### ISSUE THREAD

**Issue by exploide** [willshersystems/ansible-sshd#43]
I do not know why it is necessary for this role to explicitly manage the directory `/var/run/sshd`. But apart from that, there is an exclusion for RHEL7 but not for Fedora. I checked that a default installation of Fedora with working sshd does not have such a directory.

**Comment by mattwillsher** [comment]
There was a reason for the management of /var/run/sshd, though I can't recall it through the mists of time and it may be that it was a bone headed call on my part.

I think I'll remove it entirely when I get time. For now, you can set sshd_manage_var_run to false as a role or inventory variable.

**Comment by mattwillsher** [comment]
Now I remember. `/var/run/sshd` management is there for Docker. Much of the initial dev was in Docker and I moved to Vagrant VMs for additional testing. Under Docker, I seem to recall `/var/run` didn't exist. The [`file`](http://docs.ansible.com/ansible/file_module.html) module creates them recursively.

I'll review this again under #45 and sort it one way or another.
