### ISSUE TITLE
Outdated readme

### ISSUE THREAD

**Issue by mschneiderwind** [willshersystems/ansible-sshd#53]
The readme currently provide ansible galaxy role `mattwillsher.sshd`
This role location is leading to a 404 on galaxy.ansible.com
`[WARNING]: - mattwillsher.sshd was NOT installed successfully: - sorry, mattwillsher.sshd was not found on https://galaxy.ansible.com.`

**Comment by mattwillsher** [comment]
Thanks for raising the issue. I've updated the README.
