### ISSUE TITLE
Ansible 2.3 warnings

### ISSUE THREAD

**Issue by jabl** [willshersystems/ansible-sshd#55]
New warnings I noticed now that ansible 2.3 is in EPEL7 (slightly edited to remove unnecessary stuff):

TASK [ansible-role-sshd : Run directory] *******************************************************

 [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: {{ false if ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7' else true }}

(we're using a slightly older version of ansible-sshd, but this comes from defaults/main.yml.)

TASK [ansible-role-sshd : Service enabled and running] ***********************************************

 [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: {{ false if ansible_virtualization_type == 'docker' else true }}

(This is also from defaults/main.yml)

**Comment by mattwillsher** [comment]
Thanks for the report. I've a couple of idea how to fix this:

* remove the {{}} delimiters
* move the logic into conditional includes in the same way that the OS defaults are set

I'll look into it as soon as I have a bit of free time.

**Comment by mattwillsher** [comment]
Fixed in #57
