### ISSUE TITLE
Seeking advice on adding Alpine Linux support

### ISSUE THREAD

**Issue by snesbittsea** [willshersystems/ansible-sshd#75]
All:

I've been working on adding Alpine Linux 3.7 support to ansible-sshd. Getting it to work requires a code change beyond a new vars/Alpine.yml. I'd am more than happy to submit a pull/patch, but would appreciate input on how you want the change implemented.

The core of the problem is the validate statement in the Configuration task. Successful validation assumes that the ssh host keys have been generated as part of the install. Apparently under Alpine 3.7 this is not true. The host keys are generated when the openssh daemon is first run. Since it hasn't been run, the keys don't exist and the validation fails.

Currently I am working around that by adding a block statement prior to the Configuration task which is run if the os_family is Alpine and virtualization_type docker. The block contains two tasks - one starting the sshd server and one stopping it. With this present the Configuration task passes on Alpine Linux.

Question is whether this is an acceptable way to address the issue or if you would prefer some other approach? Or would you prefer that a patch/pull request not be submitted?

-steve

**Comment by mattwillsher** [comment]
Could you generate the keys instead? 

I think there are also other distros that generate the keys at process start time. This seems specifically for the case where sshd is running in a container? Otherwise sshd would be running as Ansible is connecting via it.

**Comment by snesbittsea** [comment]
You're right - this is a LXC container.

And as I worked through it I've actually gone down the path you suggested as follows:
`- name: Install ssh packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ sshd_packages }}"

- name: Generation SSH host keys if none are present
  command: ssh-keygen -A creates=/etc/ssh/*_key

- name: Configuration
  template:
    src: sshd_config.j2
    dest: "{{ sshd_config_file }}"
    owner: "{{ sshd_config_owner }}"
    group: "{{ sshd_config_group }}"
    mode: "{{ sshd_config_mode }}"
    validate: "{{ sshd_binary }} -t -f %s"
  notify: reload_sshd
`
I have a couple of questions/concerns regarding this approach. First I am running it for all distributions under the assumption that it isn't going to foul things up. Maybe it should only be run if host is a docker or LXC container?

Second, to make the task idempotent I am calling the ssh-keygen with a creates clause which makes the assumption that it should not be run if *any* key has been generated. It doesn't check to see if all host keys are present (and I'm not sure how to determine which host keys should be present)

-steve

**Comment by mattwillsher** [comment]
Sorry I didn't get back to this.
