### ISSUE TITLE
Fix build

### ISSUE THREAD

**Issue by mattwillsher** [willshersystems/ansible-sshd#77]
Build is failing saying ansible_virtualization_type is undefined.

**Comment by D4N** [comment]
The build is green now, I guess this can be closed then?

Although not specific for this issue, but would it be possible to release a new version? The latest version of this role that one gets from ansible galaxy does not work with the most recent ansible version.

**Comment by mattwillsher** [comment]
Fixed by #78

**Comment by mattwillsher** [comment]
v0.6.0 has just been released. Thanks for making that possible.

**Comment by D4N** [comment]
This is one of the fastest fixes I have encountered, thanks a lot!
