### ISSUE TITLE
Support for multiple ssh daemons

### ISSUE THREAD

**Issue by tterranigma** [willshersystems/ansible-sshd#80]
I have a need to configure and run 2 ssh daemons / services on different ports and generally different configuration. AFAICT this is not possible currently with this role. Would there be interest to add this functionality? I could work on a first implementation.

**Comment by mattwillsher** [comment]
I'm unclear on the use case for this. sshd supports Match blocks to adjust configuration based on User, Group, Host, and Address and individual users can have restrictions placed in their authorized_keys files.

I'm happy to consider adding the functionality if you can clearly justify the case.

**Comment by easonand** [comment]
Why not just include a separate play in your playbook with sshd_config_file, sshd_binary, sshd_service, etc. set?

---
- hosts: all
  vars:
    sshd_skip_defaults: true
    sshd:
      Compression: true
      ListenAddress:
        - "0.0.0.0"
        - "::"
      GSSAPIAuthentication: no
      Match:
        - Condition: "Group user"
          GSSAPIAuthentication: yes
    sshd_UsePrivilegeSeparation: no
    sshd_match:
        - Condition: "Group xusers"
          X11Forwarding: yes
  roles:
    - role: willshersystems.sshd

# it is fine to have more than one play in a playbook
- hosts: somehost
  vars:
    sshd_binary:
        /usr/local/sbin/sshd
    sshd_config_file:
       /usr/local/etc/ssh/sshd_config
    sshd_service:
       special-ssh
    sshd:
         Port: 
            - 9999
            - 2222
  roles:
    - role: willshersystems.sshd

**Comment by tterranigma** [comment]
@mattwillsher I cannot use Match rules as I need to have different ports for the two sshd instances.

@easonand Thank you for your suggestions. They got me thinking and I worked on #89 . The problem I encountered with your approach was that the systemd service cannot be overridden by the role user, it is hard set once depending on the OS.

Let me know what you think of #89.

**Comment by mattwillsher** [comment]
Fixed by #89 and in v0.7.0
