### ISSUE TITLE
Append sshd config

### ISSUE THREAD

**Issue by beoSheep** [willshersystems/ansible-sshd#94]
Hi,

Is it possible to Append some part of sshd_config file? My case is that I need to add some values in **AcceptEnv**, but it overwrites. Any suggestion?

**Comment by tterranigma** [comment]
There is no build in support for appending. There is [an old PR](https://github.com/willshersystems/ansible-sshd/pull/71) that you could perhaps edit.

**Comment by beoSheep** [comment]
Huh, I am not that experienced with Ansible yet. My use case is, that I have some roles which have additional **AcceptEnv** lines comparing to global sshd config, so for me it's a duplicate configuration or maybe I am doing it wrong.. :)

**Comment by mattwillsher** [comment]
AcceptEnv would need to be duplicated in your code at the moment.

**Comment by beoSheep** [comment]
Is there any plans to add such feature?

**Comment by mattwillsher** [comment]
I've been considering how such a feature could be added, but no plans at the moment. If I come up with a clean way to do it I will add it then.

**Comment by tterranigma** [comment]
@mattwillsher Personally, I can think of only two ways this could be implemented. One is what that old PR did.

The other is to have two extra variables (the names are on the spot):

- `sshd_config_append_only`: False by default, if set, the role will only append configuration to the config file.
- `sshd_config_block`: Empty by default, it contains the config snippet to append to the config file.

The current template could also use `sshd_config_block` and print eg at the end of the file. 

So, there would be 3 possibilities:

- config template only
- config template plus config block
- config block only

**Comment by Jakuje** [comment]
With OpenSSH 8.3p1 (in Fedora 32, probably others), this can be done by writing a file in drop-in directory (`/etc/ssh/sshd_config.d/`) as openssh server config supports `Include` keyword.

**Comment by mimmus** [comment]
Appending only, you give up to effectively managing your service. In other words, you haven't a "state" to apply to a service, to be sure that it has a fixed behaviour.
In any case, I agree with you that effectively overwriting the default config file is not always a a desirable behavior.
Solutions are:
- modifying inline the original file (using a module as 'lineinfile'
- dropping-in a file under /etc/yourservice.d directory, if available (as suggested above)

My 2c, even in the bad place (sorry)

**Comment by Jakuje** [comment]
Can you check if something like #158 would work for you?

**Comment by mimmus** [comment]
> Can you check if something like #158 would work for you?
Does this preserve original sshd_config file?
I hate overwriting default config file (well-formatted, full of comments and sane defaults in evidence)!

**Comment by Jakuje** [comment]
> > Can you check if something like #158 would work for you?
> 
> Does this preserve original sshd_config file?
Yes

**Comment by Jakuje** [comment]
This should be addressed with the 0.13.0 release.
